labels:
  - name: "feature"
    color: "0E8A16"
    description: "Nouvelle fonctionnalité"
  - name: "enhancement"
    color: "0E8A16"
    description: "Amélioration d'une fonctionnalité existante"
  - name: "fix"
    color: "D73A4A"
    description: "Correction de bug"
  - name: "bugfix"
    color: "D73A4A"
    description: "Correction de bug"
  - name: "bug"
    color: "D73A4A"
    description: "Rapport de bug"
  - name: "documentation"
    color: "0075CA"
    description: "Modifications de la documentation"
  - name: "chore"
    color: "FBCA04"
    description: "Tâches de maintenance"
  - name: "maintenance"
    color: "FBCA04"
    description: "Tâches de maintenance"
  - name: "major"
    color: "B60205"
    description: "Changement majeur de version"
  - name: "minor"
    color: "D4C5F9"
    description: "Changement mineur de version"
  - name: "patch"
    color: "BFD4F2"
    description: "Correction de version"
  - name: "no-issue-activity"
    color: "D73A4A"
    description: "Issue inactive"
  - name: "no-pr-activity"
    color: "D73A4A"
    description: "Pull request inactive" 