name: Draft a release note
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  draft_release:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@v5.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 